
import { Role, FleetCategory, VehicleStatus, Site, User, Vehicle, Staff, Driver } from './types';

export const SITES: Site[] = [
  { id: 'S1', name: 'PSH00001' },
  { id: 'S2', name: 'West Industrial Park' },
  { id: 'S3', name: 'East Logistics Center' },
];

export const MOCK_USERS: User[] = [
  { id: 'U1', username: 'admin', role: Role.ADMIN, assignedSiteIds: ['S1', 'S2', 'S3'], isActive: true },
  { id: 'U2', username: 'manager_s1', role: Role.MANAGER, assignedSiteIds: ['S1'], isActive: true },
  { id: 'U3', username: 'tech_s2', role: Role.TECHNICIAN, assignedSiteIds: ['S2'], isActive: true },
];

export const MOCK_VEHICLES: Vehicle[] = [
  { 
    id: 'V1', 
    vehicleNo: 'VP-526', 
    regNo: '9454-MD',
    type: 'TOYOTA PICKUP', 
    make: 'Toyota', 
    model: 'Hilux', 
    year: 2022, 
    siteId: 'S1', 
    category: FleetCategory.STS, 
    status: VehicleStatus.ACTIVE, 
    lastInspectionDate: '2024-05-15',
    ropExp: '2026-03-03',
    rasExp: '2026-02-13',
    ivmsExp: '2026-01-28',
    speedLimiter: 'AVAILABLE',
    tpiExp: 'N/A',
    mpiExp: 'N/A',
    loadTest: 'N/A',
    bucket: 'N/A',
    centreOfGravity: 'N/A',
    healthCert: 'N/A',
    civilDefence: 'N/A',
    hydroTest: 'N/A',
    tankTechnical: 'N/A',
    fifthWheel: 'N/A',
    kingPin: 'N/A',
    reliefValve: 'N/A',
    lmsValid: 'N/A',
    remark: ''
  },
  { 
    id: 'V2', 
    vehicleNo: 'VP-550', 
    regNo: '1654-BK',
    type: 'TOYOTA PICKUP', 
    make: 'Toyota', 
    model: 'Hilux', 
    year: 2021, 
    siteId: 'S1', 
    category: FleetCategory.STS, 
    status: VehicleStatus.MAINTENANCE, 
    lastInspectionDate: '2024-05-10',
    ropExp: '2025-11-17',
    rasExp: '2025-11-07',
    ivmsExp: '2026-08-16',
    speedLimiter: 'AVAILABLE',
    tpiExp: 'N/A',
    mpiExp: 'N/A',
    loadTest: 'N/A'
  },
  { 
    id: 'V6', 
    vehicleNo: 'VT-878', 
    regNo: '1229-MB',
    type: 'MIT 3TON TRUCK', 
    make: 'Mitsubishi', 
    model: 'Canter', 
    year: 2022, 
    siteId: 'S1', 
    category: FleetCategory.STS, 
    status: VehicleStatus.ACTIVE,
    ropExp: '2025-12-09',
    rasExp: '2025-12-11',
    ivmsExp: '2025-12-11',
    speedLimiter: '2025-11-27'
  },
  { 
    id: 'V7', 
    vehicleNo: 'VT-865', 
    regNo: '7422-YB',
    type: 'UD HIAB 10 TON', 
    make: 'UD', 
    model: 'Quon', 
    year: 2020, 
    siteId: 'S1', 
    category: FleetCategory.STS, 
    status: VehicleStatus.ACTIVE,
    ropExp: '2026-08-18',
    rasExp: '2026-08-25',
    ivmsExp: '2026-08-06',
    speedLimiter: '2024-08-20',
    tpiExp: '2026-07-22',
    mpiExp: '2026-07-22',
    lmsValid: '2025-10-31'
  },
  { id: 'V3', vehicleNo: 'HR-099', type: 'Pickup', make: 'Toyota', model: 'Hilux', year: 2023, siteId: 'S2', category: FleetCategory.HIRE, status: VehicleStatus.ACTIVE, lastInspectionDate: '2024-05-12' },
  { id: 'V4', vehicleNo: 'SC-204', type: 'Excavator', make: 'CAT', model: '320', year: 2020, siteId: 'S3', category: FleetCategory.SUB_CONT, status: VehicleStatus.BREAKDOWN, lastInspectionDate: '2024-04-20' },
  { id: 'V5', vehicleNo: 'STS-005', type: 'Truck', make: 'Scania', model: 'G450', year: 2022, siteId: 'S2', category: FleetCategory.STS, status: VehicleStatus.ACTIVE, lastInspectionDate: '2024-05-16' },
];

export const MOCK_STAFF: Staff[] = [
  { 
    id: 'ST_LEAD', 
    name: 'Harish Padiyar', 
    employeeId: '164562', 
    designation: 'Supervisor', 
    siteId: 'S1', 
    contact: '96772254', 
    status: 'On Leave', 
    rating: 5.0,
    avatar: 'https://i.pravatar.cc/300?u=harish',
    email: 'proj.b10.plant@stsoman.com',
    phone: '96772254',
    companyJoinDate: '07/20/2012',
    siteJoinDate: '07/02/2024',
    passportNo: 'N2856533',
    passportExpiry: '12/23/2025',
    civilId: '789562342',
    h2sExpiry: '12/23/2025',
    chemicalCourse: false,
    notes: 'N/A'
  },
  { 
    id: 'ST1', 
    name: 'Sardar John Mohamed', 
    employeeId: '164563', 
    designation: 'Forman', 
    siteId: 'S1', 
    contact: '555-0101', 
    status: 'Active', 
    rating: 4.5,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=sardar',
    email: 'sardar.jm@stsoman.com',
    phone: '555-0101',
    companyJoinDate: '01/15/2015',
    siteJoinDate: '01/15/2015',
    passportNo: 'P1234567',
    passportExpiry: '10/10/2026',
    civilId: '111222333',
    h2sExpiry: '05/05/2025',
    chemicalCourse: true,
  },
  { 
    id: 'ST2', 
    name: 'Siva Kumar', 
    employeeId: '164564', 
    designation: 'Auto Mechanic', 
    siteId: 'S2', 
    contact: '555-0102', 
    status: 'Active', 
    rating: 4.6,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=siva'
  },
  { 
    id: 'ST3', 
    name: 'Brijesh', 
    employeeId: '164565', 
    designation: 'Auto Mechanic', 
    siteId: 'S1', 
    contact: '555-0103', 
    status: 'Active', 
    rating: 4.7,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=brijesh'
  },
  { 
    id: 'ST4', 
    name: 'Ani John', 
    employeeId: '164566', 
    designation: 'Senior Auto Mechanic', 
    siteId: 'S3', 
    contact: '555-0104', 
    status: 'Active', 
    rating: 4.7,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=ani'
  },
  { 
    id: 'ST5', 
    name: 'SUBHASH GOPALAN', 
    employeeId: '164567', 
    designation: 'AUTO ELECTRICIAN', 
    siteId: 'S1', 
    contact: '555-0105', 
    status: 'Active', 
    rating: 4.8,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=subhash'
  },
  { 
    id: 'ST6', 
    name: 'JAMALI', 
    employeeId: '164568', 
    designation: 'TYRE MAN', 
    siteId: 'S2', 
    contact: '555-0106', 
    status: 'Active', 
    rating: 4.5,
    managerId: 'ST_LEAD',
    avatar: 'https://i.pravatar.cc/300?u=jamali'
  },
];

export const MOCK_DRIVERS: Driver[] = [
  { id: 'D1', name: 'Robert Brown', employeeId: 'D101', licenseNo: 'ABC-12345', licenseExpiry: '2025-12-31', assignedVehicle: 'STS-001', siteId: 'S1', status: 'On Duty' },
  { id: 'D2', name: 'Sarah Wilson', employeeId: 'D102', licenseNo: 'XYZ-67890', licenseExpiry: '2024-06-15', siteId: 'S2', status: 'Available' },
];
